_format_version: "2.1"
_transform: true

services:
- name: foggy
  url: http://foggy:8080
  plugins:
  - name: http-payload-file-log
    config:
      log_directory: home/kong
  routes:
  - name: foggy
    paths:
    - /foggy